# Generated by Django 4.1.2 on 2022-10-11 03:36

import arbol.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='codigoCatastral',
            field=models.CharField(max_length=100, validators=[arbol.validators.validar_codcat]),
        ),
        migrations.AlterField(
            model_name='predio',
            name='distrito',
            field=models.IntegerField(default=0, validators=[arbol.validators.validar_distrito]),
        ),
        migrations.AlterField(
            model_name='predio',
            name='subdistrito',
            field=models.IntegerField(default=0, validators=[arbol.validators.validar_subdistrito]),
        ),
    ]
